name: lint
on:
  push:
    branches:
      - "release"
      - "beta"
      - "main"
  pull_request:
  workflow_call:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17.6'
      - name: Install dependencies
        run: /bin/bash scripts/install_build_deps.sh
      - name: Check OpenAPI generated
        run: |
          touch server/v1/api.proto && make generate
          git diff --quiet HEAD server/v1/openapi.yaml || (echo -e "\nRun 'touch server/v1/api.proto && make generate' and check-in OpenAPI specification" && exit 1)
      - name: Install Redocly CLI
        run: npm install @redocly/cli -g
      - name: Make lint
        run: make lint
