name: release
on:
  push:
    branches:
      - "release"
      - "alpha"
      - "beta"
      - "rc"
jobs:
  lint:
    uses: ./.github/workflows/lint.yaml

  release:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --debug

